-- Create private storage bucket for uploads
-- This file is idempotent and can be run multiple times safely

-- Create the uploads bucket if it doesn't exist
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'uploads',
  'uploads',
  false, -- Private bucket - access only via signed URLs
  5242880, -- 5 MB limit (matches UPLOADS_MAX_BYTES default)
  ARRAY[
    'image/jpeg',
    'image/png',
    'image/webp',
    'image/gif',
    'image/heic',
    'application/pdf'
  ]
)
ON CONFLICT (id) DO UPDATE SET
  public = false,
  file_size_limit = 5242880,
  allowed_mime_types = ARRAY[
    'image/jpeg',
    'image/png',
    'image/webp',
    'image/gif',
    'image/heic',
    'application/pdf'
  ];

-- Storage policies for the uploads bucket
-- Note: We use server-side upload/download exclusively via signed URLs
-- These policies provide defense in depth but the primary access control
-- is through our API endpoints that generate signed URLs

-- Policy for authenticated users to upload files
-- (This is a fallback; our API does the actual authorization)
DROP POLICY IF EXISTS "Users can upload files" ON storage.objects;
CREATE POLICY "Users can upload files" ON storage.objects
  FOR INSERT
  WITH CHECK (
    bucket_id = 'uploads'
    AND auth.role() = 'authenticated'
  );

-- Policy for users to view their own uploaded files via signed URLs
-- (Again, this is defense in depth; signed URLs provide the real access control)
DROP POLICY IF EXISTS "Users can view files via signed URLs" ON storage.objects;
CREATE POLICY "Users can view files via signed URLs" ON storage.objects
  FOR SELECT
  USING (bucket_id = 'uploads');

-- No public access - all access must go through signed URLs generated by our API
-- The bucket is marked as private above, but this policy reinforces it
DROP POLICY IF EXISTS "No public access" ON storage.objects;
CREATE POLICY "No public access" ON storage.objects
  FOR ALL
  USING (false);

-- Enable RLS on storage.objects if not already enabled
ALTER TABLE storage.objects ENABLE ROW LEVEL SECURITY;

-- Add helpful comments
COMMENT ON TABLE storage.buckets IS 'Storage buckets configuration - uploads bucket is private';
COMMENT ON POLICY "Users can upload files" ON storage.objects IS 'Allows authenticated uploads to uploads bucket - API does real authorization';
COMMENT ON POLICY "Users can view files via signed URLs" ON storage.objects IS 'Enables signed URL access - API controls URL generation';
COMMENT ON POLICY "No public access" ON storage.objects IS 'Prevents public access - all access via signed URLs only';